refactor : [ISSUE-1,4] 코드 포멧팅 적용, if 문 가독성
Woo-Seok-Han/member-invite pull request #2
Opened 2023-06-29 07:53 UTC by Woo-Seok-Han

google-java-format 적용
InviteServiceImpl 그룹 매니저 체크 가독성 이슈로 수정

2023-06-29 12:08 UTC, DongHyukki requested changes
수정해주세요

2023-06-29 12:08 UTC, DongHyukki approved these changes
머지해주세요

2023-07-04 20:08 UTC, merged

2023-07-05 16:15 UTC, Woo-Seok-Han reviewed
test

2023-07-05 16:15 UTC, Woo-Seok-Han commented on src/main/java/com/zerobase/task/invite/api/common/model/ApiResponse.java
>      }
comment test

2023-07-05 16:15 UTC, Woo-Seok-Han commented on src/main/java/com/zerobase/task/invite/api/common/model/ApiResponse.java
>      }
ok